FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY requirements/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY standalone/extract_run.py ./dags/extract_run.py
COPY dags/python_scripts ./dags/python_scripts

ENV ENV=prod
ENV PYTHONPATH="/app"
CMD ["python", "dags/extract_run.py"]